#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.

set -e

echo "post deploy"

pushd ${OPENSHIFT_REPO_DIR} > /dev/null

echo "test"
bundle exec rake db:schema:load RAILS_ENV="production"
echo "post pipise"
# if echo "use $OPENSHIFT_APP_NAME; show tables" | mysql | grep attachments
# then
#     echo "Migrating DB"
#     bundle exec rake db:migrate RAILS_ENV="production"
# else
#     echo "Creating DB from schema"
#     bundle exec rake db:schema:load RAILS_ENV="production"
# fi
popd > /dev/null

if [ ! -d ${OPENSHIFT_DATA_DIR}files ]
then
	mkdir ${OPENSHIFT_DATA_DIR}files
fi

ln -sf ${OPENSHIFT_DATA_DIR}files ${OPENSHIFT_REPO_DIR}files
